### ISSUE TITLE
2.x: `examples/security/webserver-signatures` test fails with JDK 11.0.11 (works with 11.0.22)

### ISSUE THREAD

**Issue by barchetta** [helidon-io/helidon-examples#38]
This might be OK, but I wanted to at least document it. If you build `examples/security/webserver-signatures` with JDK 11.0.11 it fails with:

```
[INFO] Running io.helidon.security.examples.signatures.SignatureExampleConfigMainTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.712 s <<< FAILURE! - in io.helidon.security.examples.signatures.SignatureExampleConfigMainTest
[ERROR] io.helidon.security.examples.signatures.SignatureExampleConfigMainTest  Time elapsed: 0.712 s  <<< ERROR!
io.helidon.common.pki.PkiException: Failed to read PKCS12 keystore: keystore:FILE:/Users/jdipol/GitHub/barchetta/helidon-examples/examples/security/webserver-signatures/src/main/resources/keystore.p12
	at io.helidon.security.examples.signatures.SignatureExampleConfigMainTest.initClass(SignatureExampleConfigMainTest.java:31)
Caused by: java.io.IOException: Integrity check failed: java.security.NoSuchAlgorithmException: Algorithm HmacPBESHA256 not available
	at io.helidon.security.examples.signatures.SignatureExampleConfigMainTest.initClass(SignatureExampleConfigMainTest.java:31)
Caused by: java.security.NoSuchAlgorithmException: Algorithm HmacPBESHA256 not available
	at io.helidon.security.examples.signatures.SignatureExampleConfigMainTest.initClass(SignatureExampleConfigMainTest.java:31)
```

Works fine with JDK 11.0.22

**Comment by tomas-langer** [comment]
Not relevant anymore.
